
var makes = [['Acura'],
    ['Aston Martin'],
    ['Audi'],
    ['BMW'],
    ['Buick'],
    ['Cadillac'],
    ['Chevrolet'],
    ['Chrysler'],
    ['Dodge'],
    ['Ferrari'],
    ['Ford'],
    ['GMC'],
    ['Honda'],
    ['HUMMER'],
    ['Hyundai'],
    ['Infiniti'],
    ['Isuzu'],
    ['Jaguar'],
    ['Jeep'],
    ['Kia'],
    ['Lamborghini'],
    ['Land Rover'],
    ['Lexus'],
    ['Lincoln'],
    ['Lotus'],
    ['Maserati'],
    ['Mazda'],
    ['Mercedes-Benz'],
    ['Mercury'],
    ['MINI'],
    ['Mitsubishi'],
    ['Nissan'],
    ['Pontiac'],
    ['Porsche'],
    ['Rolls-Royce'],
    ['Saab'],
    ['Saturn'],
    ['Scion'],
    ['Smart'],
    ['Subaru'],
    ['Suzuki'],
    ['Toyota'],
    ['Volkswagen'],
    ['Volvo']
]